### ISSUE TITLE
Fails to install when add-apt-repository not installed

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/layer-beats-base#4]
bug in charmhelpers: https://bugs.launchpad.net/charm-helpers/+bug/1576666

I think this would be fixed by using the `apt` layer.

```
Traceback (most recent call last):
  File "hooks/install", line 19, in <module>
    main()
  File "/var/lib/juju/agents/unit-topbeat-0/.venv/lib/python3.4/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch()
  File "/var/lib/juju/agents/unit-topbeat-0/.venv/lib/python3.4/site-packages/charms/reactive/bus.py", line 421, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-topbeat-0/.venv/lib/python3.4/site-packages/charms/reactive/bus.py", line 404, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-topbeat-0/.venv/lib/python3.4/site-packages/charms/reactive/bus.py", line 280, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-topbeat-0/charm/reactive/beats_base.py", line 12, in install_beats_repo
    configure_sources(update=True)
  File "/var/lib/juju/agents/unit-topbeat-0/.venv/lib/python3.4/site-packages/charmhelpers/fetch/__init__.py", line 363, in configure_sources
    add_source(source, key)
  File "/var/lib/juju/agents/unit-topbeat-0/.venv/lib/python3.4/site-packages/charmhelpers/fetch/__init__.py", line 289, in add_source
    subprocess.check_call(['add-apt-repository', '--yes', source])
  File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'add-apt-repository'
```

**Comment by lazypower** [comment]
@galgalesh - I moved this over to the apt layer, which should lend a hand here i suppose. I'm not certain what stub's doing around the charm helpers bits, but it did slim down the charms a bit in a few places which I really do like 👍 

Let me know how you get along with these refactors. I've published them into cs:~containers/trusty/*beat respectively

**Comment by merlijn-sebrechts** [comment]
Thanks a lot!

 I'll test these changes and let you know if the problem is resolved.

I know Cory was talking about a system where "list"-type config items would be merged by the builder, instead of just taking the top one. Not sure how far that work has come, you might want to contact him about this.

**Comment by lazypower** [comment]
i don't think its too much to ask the top layers to carry the config options. it only applies to the core of the beats, as community beats don't seem to get packages. YMMV

**Comment by kwmonroe** [comment]
I don't see how moving to apt will fix this.  The apt layer just does a `fetch.add_source` from charmhelpers:

https://git.launchpad.net/layer-apt/tree/lib/charms/apt.py#n52

Which will eventually call out to add-apt-repo **if** the source starts with certain prefixes:

http://bazaar.launchpad.net/~charm-helpers/charm-helpers/devel/view/head:/charmhelpers/fetch/__init__.py#L285

So i'd expect that to fail if you're trying to add one of those prefixed sources whether you're using the apt layer or not.

**Comment by lazypower** [comment]
Kind of what i was thinking but i had no idea if stub was doing some magic in the backend to add that package if its missing.

I would think we want python-software-properties or software-properties-common or one of the many aliases the add-apt-repository helper has been ferreted away in to be available to anything using that layer, so it makes sense to track over on layer-apt, that it take the use case into account since we're advocating people needing to interface with apt use the layer vs calling the charm-helper directly.

Which i like, as we can eventually split that out into the layer, and nuke the charm helpers backend transparently.

I'm all for this as a pie-in-the-sky outline for how things happen 👍

**Comment by lazypower** [comment]
@galgalesh this issue is quite old now, have you encountered any further issues with missing the add-apt-repository binary on your systems? I'm under the impression that this is now added via cloudinit during the juju bootstrap sequence so it should exist.  If thats not the case, please re-open the issue and we'll address it once and for all (with a really big hammer)

**Comment by merlijn-sebrechts** [comment]
Everything seems to be working now, thanks!
